name: ChestTrap
main: com.em.chesttrap.ChestTrap
version: 0.1
commands:
 chesttrap:
  description: Defines an Chest Trap.
  usage: You have no permission to use it
  aliases: ct
permissions:
 chesttrap.create:
  description: Grants the ability to use /chesttrap.
  default: op